export const EVENTS = {
  PING: 'PING',
  UPDATE_SETTING: 'UPDATE_SETTING',
  REPLACE_SETTING: 'REPLACE_SETTING',
  MERGE_SETTING: 'MERGE_SETTING',
  WS_MESSAGE: 'WS_MESSAGE',
  NINKI: 'NINKI', // 人气
  DANMAKU: 'DANMAKU'
}

export const ERRORS = {
  SYSTEM_ERROR: 'SYSTEM_ERROR'
}

export const COMMON_RESPONSE = {
  message: 'ok'
}